### ISSUE TITLE
Please Add a download link of Version 1.x in VCC repo

### ISSUE THREAD

**Issue by embracech** [poi-vrc/DressingTools#333]
It's useful using DT 1.x for planned multiple dressing blending plan. 
DT2.x key feature makes no help if I don't need non-destructive purpose.
nd DTLegeacyEditor Triggers DT2.x as well, I cannot use it as DT1.x well

**Comment by poi-vrc** [comment]
Hi,

DTv1 itself isn't a UPM package and wasn't planned to be one previously. Only v2 by design is integrated into the UPM package structure. Therefore, adding it as a package in the VCC repository would involve quite some work.

v1 development is mostly turned down. I will probably consider it if many users want this to be included in the VCC.

The v1 version will be always available at, and the GitHub releases:
https://chocopoi.booth.pm/items/3639300

IMO, you shall always use the non-destructive approach. Would you mind to let me know what exactly you are trying to do for "multiple dressing blending plan"?

**Comment by embracech** [comment]
Okay, for my purpose of use, I'm usually using Baking on Modular Avatar to acquire an instant review for scene and model changes. I liked DT automatic placing bones and grouping PBs in places , these features helps me a lot. but I don't need automatic FX generating and wardrobe. because I'm planning FX myself. I can use baking for modular avatar support only prefabs and adjust myself. but I don't know how to bake for a instant view on DT2.x, so it seems DT1.x better for me.
On that purpose. DTLegacyEditor without FX gen and wardrobe and A BAKE button could be a better idea.

**Comment by poi-vrc** [comment]
You can try right-clicking the avatar and "bake" the avatar to achieve the similar effect. A copy of the avatar with applied modules will be generated.
![image](https://github.com/poi-vrc/DressingTools/assets/77053052/55d8a751-c643-4ac7-be46-bfc73332dae1)

**Comment by poi-vrc** [comment]
Actually, I have an idea previously to have a button just like in Blender to directly apply a modifier (aka our modules) destructively. But this still needs DT to transition from the one-configuration approach to multi-component approach (which is in the progress).

I would prefer developing something like this in the future more than to the v1 I guess. 🤔 
![image](https://github.com/poi-vrc/DressingTools/assets/77053052/b396c183-6506-469f-99a6-311edadd9c7c)

**Comment by embracech** [comment]
oops, that's quite different baking method. definitely that's a good idea applying a modifier likes blender.
Though people got hobbies in different methods. And I'm sorry that I did not read out manual complete.
Thanks for patient pointing out features.
