### ISSUE TITLE
[Feature Request] Auto Identifying Humanoid Bones

### ISSUE THREAD

**Issue by YukihoAA** [poi-vrc/DressingTools#46]
![image](https://user-images.githubusercontent.com/20253131/208291598-3815c8fb-4be4-4c00-a170-73024270f2d1.png)

It would be great if dressiong tool supports auto identify humanoid bones

like, 

Upper Arm.L == Upper_Arm.L == Left Upper Arm ==Left Arm == Left_Arm == Arm.L

**Comment by poi-vrc** [comment]
Hi, thanks for your request. But I would like to know what does adding auto-identify humanoid bones do?

Now DressingTools dress up according the matching bones regardless it's a humanoid or not, as long it has an Armature object and two armatures look similar.

**Comment by YukihoAA** [comment]
it does not works auto merge for the costume

### Avatar
RearAlice (uses Upper Arm.L)


### Cloth
SnowFlacks2 (uses Upper_arm.L) - https://booth.pm/ko/items/4362555

**Comment by poi-vrc** [comment]
DressingTools expects the avatar and clothes bone names to match in order to dress automatically.

It is really bad if the clothes' creator does not follow the original avatar's bone armature and naming and publish it to users. I have even seen some authors misspell the "Armature" object or didn't even have an armature and sold them in booth at a high price.

I could implement something like bone guessing but it would be inaccurate and bound it to another bone.

**Comment by Thelvaen** [comment]
yes, it would be a nice enhancement :)
