### ISSUE TITLE
[Feature Request] Ignore Errors

### ISSUE THREAD

**Issue by Toshy0** [poi-vrc/DressingTools#47]
Can you add an option to ignore the errors generated and just have the program try anyway
for example with the "clothes placed inside avatar" error id like to be able to ignore it because in some cases the clothing item is working as intended however there is still an error such as the situation shown below it is all located correctly but the program will not allow me to continue
![image](https://github.com/poi-vrc/DressingTools/assets/87720363/dcc54453-48cc-4523-9e16-6f9019a06f6e)

**Comment by poi-vrc** [comment]
It’s by design that you must not put the clothes prefab inside the avatar and attempt to dress it with the tool. It will cause critical issues when dressing (some users did this before).

What the tool does, is to unpack the clothes prefab and move the matching clothes bones to the avatar. You can’t just ignore the error because it does not work like that.

To dress the clothes, you must move it away from the avatar and put it to the root of the scene instead.

**Comment by poi-vrc** [comment]
Please follow carefully what the 1 minute instruction video says:
https://www.youtube.com/watch?v=9nt2dDpnDA0
